### ISSUE TITLE
Possible Mac hosting support?

### ISSUE THREAD

**Issue by GhostieSpook** [AeonLucid/Impostor#10]

**Comment by joaosombrio** [comment]
Yes it is. You can:
- install netcore3.1 and build and run
- run with docker

Impostor doesn't have a published release targeting Mac though.

**Comment by GhostieSpook** [comment]
both or one or the other

**Comment by GhostieSpook** [comment]
sorry for dumb questions. trying to figure out how this works so I can set up some game nights with my server :)

**Comment by joaosombrio** [comment]
Either one.
Building is a little bit more tricky if you don't know what you're doing.
I'd say just install docker and then run the docker command that's in the readme. Don't forget to forward 23023 UDP port on your router if you want to serve for players online.

**Comment by joaosombrio** [comment]
@GhostieSpook 
![image](https://user-images.githubusercontent.com/10300609/94290100-20154780-ff30-11ea-9c6d-5db473ce9d4b.png)
a release for osx will be added.
thank you Ghostie!

**Comment by AeonLucid** [comment]
Addressed in https://github.com/AeonLucid/Impostor/commit/f0e838be729d727b2fc74ddbe28014af1804405b. 
An osx release will be available next release.
