### ISSUE TITLE
Client nonfunctional with Among Us installed on Linux through Steam

### ISSUE THREAD

**Issue by compucat** [AeonLucid/Impostor#11]
The client does not function when attempting to patch a Steam installation of Among Us on Linux, complaining that the Among Us install directory doesn't exist.

I've tried executing the client with both Proton and straight Wine (from within Steam's wineprefix); it otherwise runs fine.

I added a symlink `drive_c/users/<username>` pointing to `drive_c/users/steamuser`, suspecting that it was looking at the wrong user directory and thus not finding AppData; this did absolutely nothing, surprisingly.

I have not tested in vanilla Wine completely without Steam as I do not own a DRM-free (itch.io) copy of Among Us.

This could easily be solved by simply adding a manual override for `regionInfo.dat`'s location; this would even allow the client to be run natively with mono on Linux instead of running within Wine.

**Comment by joaosombrio** [comment]
`regionInfo.dat` file is in `C:\Users\<user>\AppData\LocalLow\Innersloth\Among Us`. There could be a mono target for the client for people running on linux. Do you think a simple file browser control in the client would be a simple solution?

**Comment by compucat** [comment]
Absolutely; that would also simplify patching files extracted from mobile
clients.

Alternatively, Steam’s Among Us install files are in a known location
relative to the base steamapps directory on Linux; this could be added as
an additional search target.

**Comment by Mm2PL** [comment]
Very hacky solution:
  - `mkdir -p ~/.local/share/..\LocalLow/Innersloth/Among Us`
  - Copy `regionInfo.dat` from your Among Us steam version (should be `~/.steam/steam/steamapps/compatdata/945360/pfx/drive_c/users/steamuser/AppData/LocalLow/Innersloth/Among Us/regionInfo.dat`)
  - Run the program using Mono
  - Copy the `regionInfo.dat` file back

**Comment by alex9099** [comment]
@Mm2PL that still complains about not finding the file :/ 

Ran the program like so "mono Impostor.Client.exe"

**Comment by hatzel** [comment]
Just created a CLI tool for this, mostly for fun but maybe it can help someone out: https://github.com/hatzel/impose-addr

Great project by the way! It would probably be nice to get the UI working on Linux.

**Comment by compucat** [comment]
@hatzel Well done, that was fast! Works like a charm. (I really need to learn Rust, heh.)
@Mm2PL I tried that with a symlink at first; it didn't work for me, but I probably just did something wrong on my end.

I thought I'd have a go at extending the client myself, but dotnet toolchains on Linux are a royal pain to set up. Might come back and keep working on it once I can get the toolchain to play nice.

**Comment by AeonLucid** [comment]
In case you missed it, you can also use https://aeonlucid.com/Impostor/ now to generate the correct file.

**Comment by kolaente** [comment]
I found  #50 which adds a cli, but how do I use that?
