### ISSUE TITLE
Wrong lost connection with server message

### ISSUE THREAD

**Issue by MrKrakenied** [AeonLucid/Impostor#14]
![](https://media.discordapp.net/attachments/758829008237625355/759207540969439252/unknown.png)

**Comment by AeonLucid** [comment]
How do you reproduce this?

**Comment by MrKrakenied** [comment]
Join to a game and stop Impostor.Server

**Comment by AeonLucid** [comment]
Can't reproduce. 

- Killing the process: "You disconnected from the server. Sent 6 pings that remote has not responded to."
- Pressing CTRL+C: "Forcibly disconnected from the server: The remote sent a disconnect request."

This is on **2020.9.22**.
