### ISSUE TITLE
Compile for 32-bit systems?

### ISSUE THREAD

**Issue by AntINFINAit** [AeonLucid/Impostor#17]
# Feature Request
Compile for 32-bit systems.
## Feature Information:
I have an old laptop that runs my webservers and other stuff with ubuntu server 16.04. Many people probably have one of those. Is it possible to run your server on the 32-bit systems?

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by AeonLucid** [comment]
Should be possible but I would prefer if you compiled a build for yourself. I don't believe many still run x32. 

I can add instructions to the wiki on how to do so.

**Comment by AntINFINAit** [comment]
I have tried to compile with visual studio, but i get massive errors. I will try to fix them, see what happens.

**Comment by AntINFINAit** [comment]
I could also make a fork, but i don't know how to work with git.

**Comment by joaosombrio** [comment]
unfortunately netcore doesn't support linux x86 as a runtime :(
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids

**Comment by marie6324** [comment]
Found this after a couple minutes of searching; continue at your own risk. https://github.com/liserdarts/dotnetcore-build-x86-Linux

Due to the completely unsupported nature of this method and the age of the OS, I will be closing this issue.
