### ISSUE TITLE
Memory leak during gameplay

### ISSUE THREAD

**Issue by claabs** [AeonLucid/Impostor#23]
# Bug Report

## Base Information
- Operating System: Linux (Docker)
- Imposter Version: 1.0.0
- Among Us Version: 

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

During normal party gameplay, the Docker container leaks around 4GB of memory per hour.

I assume this is some sort of poorly directed log file that's just filling up the memory?

## Reproduction

Play a game (in our case, with 8/9 players). The containers memory usage will gradually increase until your system lags and the lobby crashes.

I resorted to just restarting the container every hour.

**Comment by miguemely** [comment]
Hi @claabs ,

@AeonLucid mentioned that he fixed it in the current dev release within Discord so it should be coming soon.

**Comment by AeonLucid** [comment]
You can switch to the dev release on docker for now.

**Comment by AeonLucid** [comment]
Closing because this is fixed in the dev branch.
