### ISSUE TITLE
Increase Maximum Player Limit?

### ISSUE THREAD

**Issue by myleskeeffe** [AeonLucid/Impostor#29]
# Feature Request

## Feature Information:
Is it possible to change https://github.com/AeonLucid/Impostor/blob/f5fea3962d5aa9519898d9342d4d1789ec733aaa/src/Impostor.Server/Net/Game.cs#L265 and increase the maximum player limit? I haven't yet had a chance to experiment and test it yet - but would anything be likely to break if one were to change this limit?

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by myleskeeffe** [comment]
Answered on Discord:
![image](https://user-images.githubusercontent.com/11828103/94679047-0b7ee800-0352-11eb-9333-0ffa50007ad4.png)

**Comment by ThatsFluke** [comment]
@myleskeeffe i cant find if (_players.Count >= 9)  anymore. can you give me any pointers? thanks!
