### ISSUE TITLE
docker-compose.yml and volumes regarding configs/env

### ISSUE THREAD

**Issue by TekExplorer** [AeonLucid/Impostor#33]
# Feature Request

## Feature Information:
 
Essentially, I would like to see a bind volume I could just attach for the config.json that would automatically fill it with a default configuration. this way one could actually edit the config while using docker.

either that or perhaps have env variables that can control/replace the config while docker, which may be better

I would also like to see an example docker-compose.yml that has this mount/env and showcases what can be done with it
## I confirm:
- [ + ] that I have searched for an existing feature request matching the description.

**Comment by LelouBil** [comment]
environement variables are already available 
https://github.com/AeonLucid/Impostor/wiki/Server-configuration

**Comment by TekExplorer** [comment]
oh right, i already got that cleared up in the discord. forgot to close :sweat_smile:
