### ISSUE TITLE
Disconnect when trying to join public game

### ISSUE THREAD

**Issue by cmalita** [AeonLucid/Impostor#35]
# Bug Report

## Base Information
- CentOS 7.8.2003
- Impostor 1.1.0
- Among Us v2020.9.9

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

## Symptoms 

Game gets disconnected when you try to join a public game. 

"You disconnected from the server. Reliable packet 1 (size=17) was not ack'd after 7510 ms (9 resends)

## Reproduction

1. Create a game and make it public

2. From another client click find game

3. Click the game to try and join it

**Comment by cmalita** [comment]
> Set the `PublicIp` correctly in the configuration.

Wow, thanks for the quick response, but where do I modify the config.json as I’m running the server dockerized?

**Comment by AeonLucid** [comment]
For docker you can use environment variable. Use `IMPOSTOR_Server__PublicIp`.
See for examples https://github.com/AeonLucid/Impostor/wiki/Server-configuration.

**Comment by cmalita** [comment]
> For docker you can use environment variables. Use `IMPOSTOR_Server__PublicIp`.
> 
> See for examples https://github.com/AeonLucid/Impostor/wiki/Server-configuration.

Thanks, it's fixed now.
