### ISSUE TITLE
How can Android use the server

### ISSUE THREAD

**Issue by Small-Miao** [AeonLucid/Impostor#36]
# Feature Request

## I confirm:
- [ ] that I have searched for an existing feature request matching the description.

**Comment by marie6324** [comment]
Read the readme, FAQ, or ask in the discord.  Git issue are not intended for this.

**Comment by Mm2PL** [comment]
https://aeonlucid.com/Impostor/
Open the from your Android device. It will tell you how to connect to an Impostor server.

**Comment by Saars1337** [comment]
> https://aeonlucid.com/Impostor/
> Open the from your Android device. It will tell you how to connect to an Impostor server.

404 not found

**Comment by AeonLucid** [comment]
@Saars1337 https://impostor.github.io/Impostor/
