### ISSUE TITLE
Random impostor assignment

### ISSUE THREAD

**Issue by byeze** [AeonLucid/Impostor#4]
Hi! Where's the code that selects a random player as the impostor for the game?

**Comment by Koupah** [comment]
I'm pretty sure the Host client chooses who the impostor/s are, I could be wrong though.

**Comment by byeze** [comment]
@Koupah I also think that, I din't find any references to any impostor choosing function. But let's wait for the developer.

**Comment by joaosombrio** [comment]
@Koupah @byeze That is correct. This server implementation is for a 'local region server' and not for the actual rooms. With the server on, you can create multiple rooms which are in fact inside the game itself.

**Comment by AeonLucid** [comment]
The host of the room decides all logic and shares it with the other players through GameData packets. Currently the server just copies and forwards them without reading the contents.

It might be possible to intercept and modify these packets. But I'm afraid the host will not accept it, this is something I'd have to test out though.

**Comment by byeze** [comment]
Thank you! I'll investigate more and If I try to modify the packets, I will share the pr. 👍😉
