### ISSUE TITLE
Some questions about the among us protocol

### ISSUE THREAD

**Issue by Stenlan** [AeonLucid/Impostor#42]
# Feature Request

## Feature Information:
Hey, I'm one of the devs for the among us automute application (https://github.com/denverquane/amongusdiscord). I was wondering if I could talk to you guys about some things regarding the protocol that Among Us uses. This seemed like the easiest way to contact you guys. I want to know if it might be possible (or if you think the possibility _might_ exist), on the network level, to receive game state updates without actually taking up a player spot. For example by false disconnecting or putting the player in an invalid state that will cause them to not take up a player spot anymore.

Thanks in advance!

## I confirm:
- [x ] that I have searched for an existing feature request matching the description.

**Comment by AeonLucid** [comment]
https://discord.gg/Mk3w6Tb
