### ISSUE TITLE
Config File must be reloaded at every system boot to set server IP

### ISSUE THREAD

**Issue by Akilestar** [AeonLucid/Impostor#44]
# Bug Report

## Base Information
- Raspberry Pi OS (ARM x86) - Headless
- Impostor 1.1.0
- Among Us v2020.9.22s

## I confirm:
- [x ] that I have searched for an existing bug report for this issue.

## Symptoms 

After rebooting the OS the server external IP address defaults to 127.0.0.1. Opening the config.json in nano and closing it resolves the issue, but it must be done after any reboot. 

## Reproduction

Reboot the Pi and start the server.

**Comment by AeonLucid** [comment]
Seems like a problem of your pi.
