### ISSUE TITLE
Building from Source

### ISSUE THREAD

**Issue by enbyautumn** [AeonLucid/Impostor#47]
# Feature Request

## Feature Information:
Add a real Building from Source section in the Wiki, it would be very helpful

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by js6pak** [comment]
1. clone
2. `dotnet build`

**Comment by Mm2PL** [comment]
On Linux you have to be sure not to build the client, since that probably won't build.

**Comment by fancythedeveloper** [comment]
My steps:

1. Install .NET Core SDK
2. Clone the repository or Download ZIP
3. Open CMD
4. `dotnet run`

**Comment by hplewis** [comment]
Getting it to build on Arch wasn't super clear with .NET 5.0, but pretty easy once I figured it out. Basically, I had to do:

1. Download the [`dotnet-install.sh` script](https://dot.net/v1/dotnet-install.sh) & make it executable (`chmod +x dotnet-install.sh`).
2. Run `sudo ./dotnet-install.sh --install-dir /usr/share/dotnet -channel Current -version 5.0.100-rc.1.20452.10`
3. `cd src/Impostor.Server && dotnet build`

The latest .NET version can be found [here](https://dotnet.microsoft.com/download/dotnet/5.0).

If you try to run the `dotnet-install.sh` script with the `latest` version, as of today, it only installs 3.x.x. You have to specify an exact 5.x.x version.
