### ISSUE TITLE
More configuration?

### ISSUE THREAD

**Issue by thetayloredman** [AeonLucid/Impostor#57]
# Feature Request

## Feature Information:

The ability to configure detailed game settings such as:

* Max player count
* no. Impostors
* etc.

## I confirm:
- [x] that I have searched for an existing feature request matching the description.

**Comment by ilikestohack** [comment]
YES GIVE

**Comment by thetayloredman** [comment]
YES GIVE

**Comment by Mm2PL** [comment]
It's impossible to increase the player limit past 10 due to the client's design. That makes changing the count of impostors infeasible to do as well.

**Comment by ilikestohack** [comment]
> 
> 
> It's impossible to increase the player limit past 10 due to the client's design. That makes changing the count of impostors infeasible to do as well.

no way to edit it client side? :(

**Comment by Mm2PL** [comment]
> > It's impossible to increase the player limit past 10 due to the client's design. That makes changing the count of impostors infeasible to do as well.
> 
> no way to edit it client side? :(

There are possibilities to do that but those are out of scope of this project.

**Comment by thetayloredman** [comment]
Because all the client modifies is the regionInfo.dat file?

**Comment by thetayloredman** [comment]
*confused emoji*
@Mm2PL 

As in, there is no actual game files modified and it's just the `regionInfo.dat` file that stores server location - server ip data?

**Comment by reecebenson** [comment]
> Because all the client modifies is the regionInfo.dat file?

Correct - this project isn't for modifying the Among Us game client. The Impostor.Client package is just for updating the `regionInfo.dat` file.

**Comment by Mm2PL** [comment]
> _confused emoji_
> @Mm2PL
> 
> As in, there is no actual game files modified and it's just the `regionInfo.dat` file that stores server location - server ip data?

yep

**Comment by thetayloredman** [comment]
Alright thanks for the information.

**Comment by HerobrineGamesYT** [comment]
What about changing certain settings? Is it possible to make something like 0s kill cooldown server side?

**Comment by Mm2PL** [comment]
>What about changing certain settings? Is it possible to make something like 0s kill cooldown server side?

That's possible but arguably plugin territory IMO
