### ISSUE TITLE
Remove game lobby timeout

### ISSUE THREAD

**Issue by ilikestohack** [AeonLucid/Impostor#58]
# Feature Request

## Feature Information:
Would be nice to see a config option to disable the lobby timeout so people have more time to join the game

## I confirm:
- that I have searched for an existing feature request matching the description.

**Comment by AeonLucid** [comment]
There is none at this moment.

**Comment by JerryGreen** [comment]
But there is D:
![image](https://user-images.githubusercontent.com/13215662/128118447-8265a102-e6b6-4a28-ba6e-e9701017bc19.png)
